### ISSUE TITLE
TypeError: t is undefined

### ISSUE THREAD

**Issue by soubhikchatterjee** [f3oall/awesome-notifications#38]
**Describe the bug**
Exception `TypeError: t is undefined` (attached screenshot)

**To Reproduce**
Steps to reproduce the behaviour:
Happens intermittently and doesn't have any particular way to replicate this error

**Expected behaviour**
Should handle exceptions

**Screenshots**

![image](https://user-images.githubusercontent.com/863672/70206176-9f8d1c80-174c-11ea-8f7b-d4c4dd0fbb08.png)

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] Ubuntu 18.04
 - Browser [e.g. chrome, safari] Firefox
 - Version [e.g. 22] 70.0.1 (64-bit)

**Additional context**
I have installed this as an npm module and using it in one of my react application.

**Comment by soubhikchatterjee** [comment]
HI Again

Is this something fixable?

**Comment by f3oall** [comment]
Hey,

Can you please create a CodeOpen (or any other service you prefer) example? I can't reproduce your issue on my local machine.

**Comment by soubhikchatterjee** [comment]
Hello there

I know it's not easy to reproduce this issue easily, it could be happening because of React's component mount/unmount cycles. I am really not sure to be very honest.

To be on a safe side, we should add a proper check on line #310 that if the element `t` is not found, it should at least not throw an error.

**Comment by soubhikchatterjee** [comment]
Please accept the pull request https://github.com/f3oall/awesome-notifications/pull/39

**Comment by soubhikchatterjee** [comment]
@f3oall 
Any chances you can merge the PR I submitted in my last post?

**Comment by f3oall** [comment]
Until you can't provide an example with reproduced error, I can't accept your PR, because the condition you added is excess, imho. Normally it's always an 'el' there, so most likely issue is in your code, where you use this library.

**Comment by smitroshin** [comment]
Hi, i have the same issue. When loading effect of notification toast is ~95% progress, and you fire notification again, in console appear error message.

You can try simulate error here (open browser console instead of codesanbox console):
https://codesandbox.io/s/awesome-notifications-issue-svjl5

Some screenshots:
![Screen Shot 2019-12-26 at 15 39 29](https://user-images.githubusercontent.com/20210690/71478470-867e0580-27f8-11ea-9428-7a6be3eb9dce.png)
![Screen Shot 2019-12-26 at 15 39 52](https://user-images.githubusercontent.com/20210690/71478469-867e0580-27f8-11ea-823e-bbd64e0ca185.png)
![2019-12-26 15-30-33](https://user-images.githubusercontent.com/20210690/71478725-c09bd700-27f9-11ea-83c7-0b9b8a6edea8.gif)

**Comment by soubhikchatterjee** [comment]
I am glad someone else has also encountered this problem.

@f3oall I hope the example/link shared in the previous post will be sufficient for you to fix the issue?


Thanks

**Comment by soubhikchatterjee** [comment]
@f3oall Any chances this will be fixed? or should i used a forked version (with my patch) of this repo for my projects?

Thanks

**Comment by Nickfrm** [comment]
Hey guys,
Sorry for that long delay, this issue fixed in v3.1.1.
Thanks for your participation!

**Comment by soubhikchatterjee** [comment]
Even after such a long delay the problem still exists in 3.1.1

![image](https://user-images.githubusercontent.com/863672/80983143-decdaf80-8e49-11ea-9c2d-282bc03a2a44.png)

**Comment by soubhikchatterjee** [comment]
After waiting for 5+ months of this bug being unresolved, i have finally switched to  alertifyjs.com since my project was suffering due to this error.

Thanks anyway.
